backend:
  name: git-gateway
  branch: main  # Ваша основная ветка на GitHub

media_folder: "static/img"  # Папка для хранения медиа-файлов
public_folder: "/img"  # Путь к медиа-файлам на сайте

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"  # Папка, где будут храниться записи
    create: true  # Возможность создавать новые записи
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # Формат URL записи
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
